import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/adgedoutlogo.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div class="flex items-center justify-between w-full">
            <div className="w-1/3">
              <Image
                src={profilePic}
                alt="CodeBucks"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="SALMAN ZUBERI HUSSAIN"
                className="!text-2xl !text-left"
              />
              <p>
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <br></br>
              <br></br>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/SHR.pdf"
                  target={'_blank'}
                  className="flex items-center bg-dark text-light p-2.5 px-6 
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border border-solid border-transparent hover: border-dark
                "
                  download={true}
                >
                  RESUME <LinkArrow className={'w-6 m1-1'} />
                </Link>
                <Link
                  href="mailto:s.hasan@unguarded.com"
                  target={'_blank'}
                  className="ml-4 text-lg font-medium capitalize text-dark underline"
                >
                  CONTACT
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div>
          <Image src={lightBulb} alt="Codebucks" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
